const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync('frontend/public/design-lab/proposals/purchase-issues.js','utf8');
const nodes={};const node=()=>({dataset:{},appendChild(){},after(){},addEventListener(){},innerHTML:'',textContent:''});
const document={head:node(),createElement:node,querySelector:()=>node(),addEventListener:(name,fn)=>{nodes[name]=fn}};
const content=node(),error=node();let renders=0,modalCalls=0;
const ctx={document,demo:{role:'采购员',view:'待采购'},tab:'todo',prs:[['TX26005','包装线']],extraProjects:[],ownerProject:{TX26005:['小李']},withinScope:n=>n==='小李',safe:s=>String(s).replaceAll('<','&lt;'),render:()=>renders++,$:s=>s==='#content'?content:error,toast(){},closeModal(){},show(){modalCalls++},stageSelection:{},URL:{revokeObjectURL(){},createObjectURL(){return 'blob:test'}}};
vm.createContext(ctx);vm.runInContext(source,ctx);
assert(vm.runInContext('issueNeedsSource()',ctx));
vm.runInContext("issueDraft.type='系统不好用'",ctx);assert(!vm.runInContext('issueNeedsSource()',ctx));
vm.runInContext("tab='issues';render()",ctx);assert(content.innerHTML.includes('反馈一个问题'));assert(content.innerHTML.includes('我提交过的'));
nodes.submit({target:{id:'issue-form'},preventDefault(){}});assert(error.textContent.includes('说说'));
vm.runInContext("issueDraft.description='增加筛选';",ctx);nodes.submit({target:{id:'issue-form'},preventDefault(){}});assert(vm.runInContext("issueRecords[0].title==='增加筛选'&&issueRecords[0].state==='已提交'",ctx));
vm.runInContext("issueDraft.type='物料有问题';issueDraft.description='型号不符'",ctx);nodes.submit({target:{id:'issue-form'},preventDefault(){}});assert(error.textContent.includes('项目和设备'));
vm.runInContext("issueDraft.project='TX26005';issueDraft.equipment='TX26005–01A'",ctx);nodes.submit({target:{id:'issue-form'},preventDefault(){}});assert(vm.runInContext("issueRecords[0].title==='TX26005–01A 型号不符'",ctx));
assert(content.innerHTML.includes('提交给我的'));assert(!content.innerHTML.includes('使用帮助'));
assert.equal(vm.runInContext('receivedIssues().length',ctx),2);
vm.runInContext("demo.role='采购经理';render()",ctx);assert.equal(vm.runInContext('receivedIssues().length',ctx),1);assert(content.innerHTML.includes('供应商补发安排待协调'));assert(!content.innerHTML.includes('G120 外观损坏'));
vm.runInContext("demo.role='采购总监';render()",ctx);assert.equal(vm.runInContext('receivedIssues().length',ctx),1);assert(content.innerHTML.includes('长周期物料交期风险'));assert(!content.innerHTML.includes('供应商补发安排待协调'));
assert.equal(modalCalls,0);
console.log('PASS: issues page, source rules, required description, local submission and history. DOM stub only.');
