"""performance deposit

Revision ID: 125c5a314415
Revises: 604478c1973e
Create Date: 2026-09-20 18:13:00.273519

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '125c5a314415'
down_revision: str | None = '604478c1973e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('performance_deposit', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('project', sa.Column('performance_deposit_return_date', sa.Date(), nullable=True))
    op.add_column('project', sa.Column('performance_deposit_returned', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'performance_deposit_returned')
    op.drop_column('project', 'performance_deposit_return_date')
    op.drop_column('project', 'performance_deposit')
    # ### end Alembic commands ###
