"""purchasing: supplier/supplier_quote + request.supplier_id

Revision ID: 21c1f5629a96
Revises: 7eb8af46c98b
Create Date: 2026-09-20 19:19:12.054619

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '21c1f5629a96'
down_revision: str | None = '7eb8af46c98b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=True),
    sa.Column('contact_name', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('payment_terms', sa.String(length=128), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier')),
    sa.UniqueConstraint('code', name=op.f('uq_supplier_code')),
    sa.UniqueConstraint('name', name=op.f('uq_supplier_name'))
    )
    op.create_table('supplier_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.String(length=32), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('project_no', sa.String(length=16), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='CNY', nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('min_qty', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('lead_days', sa.Integer(), nullable=True),
    sa.Column('price_type', sa.String(length=8), server_default='报价', nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_no'], ['item.item_no'], name=op.f('fk_supplier_quote_item_no_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_no'], ['project.project_no'], name=op.f('fk_supplier_quote_project_no_project')),
    sa.ForeignKeyConstraint(['recorded_by'], ['app_user.id'], name=op.f('fk_supplier_quote_recorded_by_app_user')),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_supplier_quote_supplier_id_supplier'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_quote'))
    )
    op.add_column('purchase_request', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_purchase_request_supplier_id_supplier'), 'purchase_request', 'supplier', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_purchase_request_supplier_id_supplier'), 'purchase_request', type_='foreignkey')
    op.drop_column('purchase_request', 'supplier_id')
    op.drop_table('supplier_quote')
    op.drop_table('supplier')
    # ### end Alembic commands ###
