"""project received_docs

Revision ID: 2e9257adb701
Revises: 4dd2bf9b19ba
Create Date: 2026-09-20 17:14:39.784578

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '2e9257adb701'
down_revision: str | None = '4dd2bf9b19ba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('received_docs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'received_docs')
    # ### end Alembic commands ###
