"""library: std_category/std_class/item; purchase_request use item_no

Revision ID: 40d6abbf8d06
Revises: b8c7207b61b5
Create Date: 2026-09-20 18:34:00.909485

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '40d6abbf8d06'
down_revision: str | None = 'b8c7207b61b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('std_category',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_std_category'))
    )
    op.create_table('std_class',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('category_code', sa.String(length=8), nullable=False),
    sa.Column('spec_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seq', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_code'], ['std_category.code'], name=op.f('fk_std_class_category_code_std_category')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_std_class'))
    )
    op.create_table('item',
    sa.Column('item_no', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('project_no', sa.String(length=16), nullable=True),
    sa.Column('std_class_code', sa.String(length=16), nullable=True),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spec_text', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=16), server_default='件', nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('mfr_model', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(source_type = '标准件' AND project_no IS NULL) OR (source_type <> '标准件' AND project_no IS NOT NULL)", name=op.f('ck_item_item_scope')),
    sa.ForeignKeyConstraint(['project_no'], ['project.project_no'], name=op.f('fk_item_project_no_project')),
    sa.ForeignKeyConstraint(['std_class_code'], ['std_class.code'], name=op.f('fk_item_std_class_code_std_class')),
    sa.PrimaryKeyConstraint('item_no', name=op.f('pk_item'))
    )
    op.add_column('purchase_request', sa.Column('item_no', sa.String(length=32), nullable=False))
    op.create_foreign_key(op.f('fk_purchase_request_item_no_item'), 'purchase_request', 'item', ['item_no'], ['item_no'])
    op.drop_column('purchase_request', 'model')
    op.drop_column('purchase_request', 'item_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_request', sa.Column('item_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('purchase_request', sa.Column('model', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_purchase_request_item_no_item'), 'purchase_request', type_='foreignkey')
    op.drop_column('purchase_request', 'item_no')
    op.drop_table('item')
    op.drop_table('std_class')
    op.drop_table('std_category')
    # ### end Alembic commands ###
