"""task table

Revision ID: 41eaaf1e1ccc
Revises: 40d6abbf8d06
Create Date: 2026-09-20 18:46:39.436306

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '41eaaf1e1ccc'
down_revision: str | None = '40d6abbf8d06'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_no', sa.String(length=24), nullable=False),
    sa.Column('project_no', sa.String(length=16), nullable=False),
    sa.Column('equip_no', sa.String(length=16), nullable=True),
    sa.Column('task_type', sa.String(length=16), nullable=False),
    sa.Column('profession', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('plan_start', sa.Date(), nullable=True),
    sa.Column('plan_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='待开始', nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ref_type', sa.String(length=24), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('ref_no', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], name=op.f('fk_task_owner_id_app_user')),
    sa.ForeignKeyConstraint(['project_no'], ['project.project_no'], name=op.f('fk_task_project_no_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
