"""init platform + numbering + project

Revision ID: 4dd2bf9b19ba
Revises: 
Create Date: 2026-09-20 16:57:45.535501

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '4dd2bf9b19ba'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer')),
    sa.UniqueConstraint('code', name=op.f('uq_customer_code')),
    sa.UniqueConstraint('name', name=op.f('uq_customer_name'))
    )
    op.create_table('number_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('template', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=32), server_default='global', nullable=False),
    sa.Column('start_value', sa.Integer(), server_default='1', nullable=False),
    sa.Column('step', sa.Integer(), server_default='1', nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_number_rule')),
    sa.UniqueConstraint('object_type', name=op.f('uq_number_rule_object_type'))
    )
    op.create_table('org',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['org.id'], name=op.f('fk_org_parent_id_org')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org')),
    sa.UniqueConstraint('code', name=op.f('uq_org_code'))
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission')),
    sa.UniqueConstraint('code', name=op.f('uq_permission_code'))
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('code', name=op.f('uq_role_code'))
    )
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], name=op.f('fk_app_user_org_id_org')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('username', name=op.f('uq_app_user_username'))
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('wechat', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('role_tag', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_contact_customer_id_customer'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact'))
    )
    op.create_table('number_seq',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('scope_key', sa.String(length=64), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['number_rule.id'], name=op.f('fk_number_seq_rule_id_number_rule'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'scope_key', name=op.f('pk_number_seq'))
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name=op.f('fk_role_permission_permission_id_permission'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_role_permission_role_id_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permission'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_ref', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_audit_log_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('project',
    sa.Column('project_no', sa.String(length=16), nullable=False),
    sa.Column('project_name', sa.String(length=128), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('project_desc', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('deal_mode', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('site_address', sa.String(length=255), nullable=True),
    sa.Column('is_retrofit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('product_type', sa.String(length=64), nullable=True),
    sa.Column('required_cycle', sa.String(length=64), nullable=True),
    sa.Column('required_capacity', sa.String(length=64), nullable=True),
    sa.Column('est_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expect_sign_date', sa.Date(), nullable=True),
    sa.Column('competitor', sa.String(length=128), nullable=True),
    sa.Column('related_project_no', sa.String(length=16), nullable=True),
    sa.Column('risk_note', sa.String(length=255), nullable=True),
    sa.Column('sales_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount_tax_incl', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('contract_no_customer', sa.String(length=64), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('warranty_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('penalty_note', sa.String(length=255), nullable=True),
    sa.Column('acceptance_standard', sa.Text(), nullable=True),
    sa.Column('designated_brand', sa.Text(), nullable=True),
    sa.Column('delivery_mode', sa.String(length=32), nullable=True),
    sa.Column('site_condition', sa.Text(), nullable=True),
    sa.Column('is_batch_delivery', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('tech_agreement_frozen', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('stage', sa.String(length=16), server_default='线索', nullable=False),
    sa.Column('close_reason', sa.String(length=32), nullable=True),
    sa.Column('close_note', sa.String(length=255), nullable=True),
    sa.Column('warranty_start', sa.Date(), nullable=True),
    sa.Column('warranty_end', sa.Date(), nullable=True),
    sa.Column('pm_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_project_created_by_app_user')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_project_customer_id_customer')),
    sa.ForeignKeyConstraint(['pm_id'], ['app_user.id'], name=op.f('fk_project_pm_id_app_user')),
    sa.ForeignKeyConstraint(['sales_id'], ['app_user.id'], name=op.f('fk_project_sales_id_app_user')),
    sa.PrimaryKeyConstraint('project_no', name=op.f('pk_project'))
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_user_role_role_id_role'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_user_role_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_role'))
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_no', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('is_frozen', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_no'], ['project.project_no'], name=op.f('fk_attachment_project_no_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_user.id'], name=op.f('fk_attachment_uploaded_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment'))
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_no', sa.String(length=16), nullable=False),
    sa.Column('equip_no', sa.String(length=16), nullable=False),
    sa.Column('equip_name', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=True),
    sa.Column('line_no', sa.String(length=16), nullable=True),
    sa.Column('seq_no', sa.Integer(), nullable=True),
    sa.Column('letter', sa.String(length=4), nullable=True),
    sa.Column('bom_complete', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_no'], ['project.project_no'], name=op.f('fk_equipment_project_no_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment')),
    sa.UniqueConstraint('project_no', 'equip_no', name='uq_equipment_project_no')
    )
    op.create_table('payment_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_no', sa.String(length=16), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=64), nullable=False),
    sa.Column('percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expect_date', sa.Date(), nullable=True),
    sa.Column('condition', sa.String(length=255), nullable=True),
    sa.Column('received_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_no'], ['project.project_no'], name=op.f('fk_payment_term_project_no_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_term')),
    sa.UniqueConstraint('project_no', 'seq', name='uq_payment_term_project_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_term')
    op.drop_table('equipment')
    op.drop_table('attachment')
    op.drop_table('user_role')
    op.drop_table('project')
    op.drop_table('audit_log')
    op.drop_table('role_permission')
    op.drop_table('number_seq')
    op.drop_table('contact')
    op.drop_table('app_user')
    op.drop_table('role')
    op.drop_table('permission')
    op.drop_table('org')
    op.drop_table('number_rule')
    op.drop_table('customer')
    # ### end Alembic commands ###
