"""project delivery_days

Revision ID: 604478c1973e
Revises: 2e9257adb701
Create Date: 2026-09-20 17:27:48.170918

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '604478c1973e'
down_revision: str | None = '2e9257adb701'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('delivery_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'delivery_days')
    # ### end Alembic commands ###
