"""purchase flow: order/ship/receive + goods_receipt

Revision ID: 7eb8af46c98b
Revises: f003b447cafe
Create Date: 2026-09-20 19:13:33.816088

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7eb8af46c98b'
down_revision: str | None = 'f003b447cafe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_no', sa.String(length=32), nullable=False),
    sa.Column('project_no', sa.String(length=16), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('item_no', sa.String(length=32), nullable=True),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('deliver_to', sa.String(length=16), server_default='公司仓库', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='待验收', nullable=False),
    sa.Column('inspected_by', sa.Integer(), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspect_note', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspected_by'], ['app_user.id'], name=op.f('fk_goods_receipt_inspected_by_app_user')),
    sa.ForeignKeyConstraint(['project_no'], ['project.project_no'], name=op.f('fk_goods_receipt_project_no_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['purchase_request.id'], name=op.f('fk_goods_receipt_request_id_purchase_request')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipt'))
    )
    op.add_column('purchase_request', sa.Column('po_no', sa.String(length=64), nullable=True))
    op.add_column('purchase_request', sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('purchase_request', sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('purchase_request', sa.Column('shipped_at', sa.Date(), nullable=True))
    op.add_column('purchase_request', sa.Column('arrived_at', sa.Date(), nullable=True))
    op.add_column('purchase_request', sa.Column('qty_received', sa.Numeric(precision=14, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_request', 'qty_received')
    op.drop_column('purchase_request', 'arrived_at')
    op.drop_column('purchase_request', 'shipped_at')
    op.drop_column('purchase_request', 'amount')
    op.drop_column('purchase_request', 'unit_price')
    op.drop_column('purchase_request', 'po_no')
    op.drop_table('goods_receipt')
    # ### end Alembic commands ###
