"""supplier_catalog

Revision ID: 8ef65ec1c45e
Revises: 21c1f5629a96
Create Date: 2026-09-20 19:24:23.076895

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '8ef65ec1c45e'
down_revision: str | None = '21c1f5629a96'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('std_class_code', sa.String(length=16), nullable=True),
    sa.Column('item_no', sa.String(length=32), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('lead_days', sa.Integer(), nullable=True),
    sa.Column('min_qty', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_no'], ['item.item_no'], name=op.f('fk_supplier_catalog_item_no_item')),
    sa.ForeignKeyConstraint(['std_class_code'], ['std_class.code'], name=op.f('fk_supplier_catalog_std_class_code_std_class')),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_supplier_catalog_supplier_id_supplier'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_catalog'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_catalog')
    # ### end Alembic commands ###
