"""warehouse: location/stock/move/material_issue

Revision ID: 9ebae32647d7
Revises: 8ef65ec1c45e
Create Date: 2026-09-20 19:30:59.025160

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '9ebae32647d7'
down_revision: str | None = '8ef65ec1c45e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse_location')),
    sa.UniqueConstraint('warehouse', 'code', name='uq_location_warehouse_code')
    )
    op.create_table('material_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_no', sa.String(length=32), nullable=False),
    sa.Column('project_no', sa.String(length=16), nullable=False),
    sa.Column('equip_no', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='待备料', nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_by', sa.Integer(), nullable=True),
    sa.Column('picked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_to', sa.String(length=64), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['picked_by'], ['app_user.id'], name=op.f('fk_material_issue_picked_by_app_user')),
    sa.ForeignKeyConstraint(['project_no'], ['project.project_no'], name=op.f('fk_material_issue_project_no_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['app_user.id'], name=op.f('fk_material_issue_requested_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_issue'))
    )
    op.create_table('material_issue_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.String(length=32), nullable=False),
    sa.Column('qty_required', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('qty_issued', sa.Numeric(precision=14, scale=3), server_default='0', nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('shortage', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('for_part', sa.String(length=48), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['material_issue.id'], name=op.f('fk_material_issue_line_issue_id_material_issue'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_no'], ['item.item_no'], name=op.f('fk_material_issue_line_item_no_item')),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_location.id'], name=op.f('fk_material_issue_line_location_id_warehouse_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_issue_line'))
    )
    op.create_table('stock_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.String(length=32), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('qty_on_hand', sa.Numeric(precision=14, scale=3), server_default='0', nullable=False),
    sa.Column('qty_locked', sa.Numeric(precision=14, scale=3), server_default='0', nullable=False),
    sa.Column('batch_no', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_no'], ['item.item_no'], name=op.f('fk_stock_item_item_no_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_location.id'], name=op.f('fk_stock_item_location_id_warehouse_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_item')),
    sa.UniqueConstraint('item_no', 'location_id', name='uq_stock_item_location')
    )
    op.create_table('stock_move',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.String(length=32), nullable=False),
    sa.Column('move_type', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('project_no', sa.String(length=16), nullable=True),
    sa.Column('equip_no', sa.String(length=16), nullable=True),
    sa.Column('ref_type', sa.String(length=24), nullable=True),
    sa.Column('ref_no', sa.String(length=32), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('moved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['warehouse_location.id'], name=op.f('fk_stock_move_from_location_id_warehouse_location')),
    sa.ForeignKeyConstraint(['item_no'], ['item.item_no'], name=op.f('fk_stock_move_item_no_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['app_user.id'], name=op.f('fk_stock_move_operator_id_app_user')),
    sa.ForeignKeyConstraint(['project_no'], ['project.project_no'], name=op.f('fk_stock_move_project_no_project')),
    sa.ForeignKeyConstraint(['to_location_id'], ['warehouse_location.id'], name=op.f('fk_stock_move_to_location_id_warehouse_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_move'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_move')
    op.drop_table('stock_item')
    op.drop_table('material_issue_line')
    op.drop_table('material_issue')
    op.drop_table('warehouse_location')
    # ### end Alembic commands ###
