"""initiation: member/milestone/purchase_request

Revision ID: b8c7207b61b5
Revises: 125c5a314415
Create Date: 2026-09-20 18:28:21.768332

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b8c7207b61b5'
down_revision: str | None = '125c5a314415'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_no', sa.String(length=16), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('plan_start', sa.Date(), nullable=True),
    sa.Column('plan_end', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_end', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='未开始', nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], name=op.f('fk_milestone_owner_id_app_user')),
    sa.ForeignKeyConstraint(['project_no'], ['project.project_no'], name=op.f('fk_milestone_project_no_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestone'))
    )
    op.create_table('project_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_no', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_role', sa.String(length=32), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_no'], ['project.project_no'], name=op.f('fk_project_member_project_no_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_project_member_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_member')),
    sa.UniqueConstraint('project_no', 'project_role', name='uq_project_member_role')
    )
    op.create_table('purchase_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_no', sa.String(length=16), nullable=False),
    sa.Column('equip_no', sa.String(length=16), nullable=True),
    sa.Column('item_name', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=16), server_default='长周期', nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=True),
    sa.Column('supplier_name', sa.String(length=128), nullable=True),
    sa.Column('need_date', sa.Date(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('ordered_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='待采购', nullable=False),
    sa.Column('is_long_lead', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_no'], ['project.project_no'], name=op.f('fk_purchase_request_project_no_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_request'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_request')
    op.drop_table('project_member')
    op.drop_table('milestone')
    # ### end Alembic commands ###
