"""purchase: deliver_to/address + status line

Revision ID: d2b3f01c7bd7
Revises: 9ebae32647d7
Create Date: 2026-09-20 19:36:25.308856

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd2b3f01c7bd7'
down_revision: str | None = '9ebae32647d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_request', sa.Column('deliver_to', sa.String(length=16), nullable=True))
    op.add_column('purchase_request', sa.Column('deliver_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_request', 'deliver_address')
    op.drop_column('purchase_request', 'deliver_to')
    # ### end Alembic commands ###
