"""engineering: drawing/drawing_version/bom_item

Revision ID: f003b447cafe
Revises: 41eaaf1e1ccc
Create Date: 2026-09-20 18:50:28.890700

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'f003b447cafe'
down_revision: str | None = '41eaaf1e1ccc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawing',
    sa.Column('drawing_no', sa.String(length=48), nullable=False),
    sa.Column('scheme', sa.String(length=24), server_default='MECH_LEVEL', nullable=False),
    sa.Column('project_no', sa.String(length=16), nullable=False),
    sa.Column('equip_no', sa.String(length=16), nullable=False),
    sa.Column('l1', sa.String(length=2), server_default='00', nullable=False),
    sa.Column('l2', sa.String(length=2), server_default='00', nullable=False),
    sa.Column('l3', sa.String(length=2), server_default='00', nullable=False),
    sa.Column('l4', sa.String(length=2), server_default='00', nullable=False),
    sa.Column('parent_drawing_no', sa.String(length=48), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=8), server_default='机械', nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), server_default='1', nullable=False),
    sa.Column('unit', sa.String(length=16), server_default='件', nullable=False),
    sa.Column('source_type', sa.String(length=16), server_default='自制件', nullable=False),
    sa.Column('current_version', sa.String(length=8), server_default='V1', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='草稿', nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_part', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], name=op.f('fk_drawing_owner_id_app_user')),
    sa.ForeignKeyConstraint(['project_no'], ['project.project_no'], name=op.f('fk_drawing_project_no_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drawing_no', name=op.f('pk_drawing'))
    )
    op.create_table('bom_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_no', sa.String(length=16), nullable=False),
    sa.Column('parent_ref', sa.String(length=48), nullable=False),
    sa.Column('child_item_no', sa.String(length=32), nullable=False),
    sa.Column('bom_source', sa.String(length=16), server_default='DESIGN', nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), server_default='1', nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('pos_no', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_item_no'], ['item.item_no'], name=op.f('fk_bom_item_child_item_no_item')),
    sa.ForeignKeyConstraint(['project_no'], ['project.project_no'], name=op.f('fk_bom_item_project_no_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bom_item'))
    )
    op.create_table('drawing_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drawing_no', sa.String(length=48), nullable=False),
    sa.Column('version', sa.String(length=8), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drawing_no'], ['drawing.drawing_no'], name=op.f('fk_drawing_version_drawing_no_drawing'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by'], ['app_user.id'], name=op.f('fk_drawing_version_published_by_app_user')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['app_user.id'], name=op.f('fk_drawing_version_reviewed_by_app_user')),
    sa.ForeignKeyConstraint(['submitted_by'], ['app_user.id'], name=op.f('fk_drawing_version_submitted_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drawing_version'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drawing_version')
    op.drop_table('bom_item')
    op.drop_table('drawing')
    # ### end Alembic commands ###
